# You can declare a list of folders you want to directly replace in the variable name REPLACE. 
# The module installer script will pickup this variable and create .replace files for you. 

REPLACE="
/system/app/MiuiScreenRecorder 
/system/app/PowerKeeper
/system/priv-app/Velvet
/system/app/FM 
/system/app/MiLinkService 
/system/app/PowerChecker
/system/app/XiaomiAccount 
/system/priv-app/QuickSearchBox 
/system/app/PaymentService
/system/priv-app/Browser
/system/priv-app/SoundRecorder
/system/priv-app/DownloadProviderUi 
/system/priv-app/Backup 
/system/app/MiCloudSync
/system/app/MiuiDaemon 
/system/app/HybridPlatform 
/system/app/VsimCore 
/system/priv-app/MiWebView
/system/app/XiaomiSimActivateService 
/system/app/MiGalleryLockscreen 
/system/priv-app/Music 
/system/priv-app/Calendar
/system/app/KSICibaEngine 
/system/app/MiuiCompass 
/system/app/MiDrive 
/system/priv-app/PersonalAssistant 
/system/app/BugReport
/system/app/CloudPrint2 
/system/priv-app/CloudBackup 
/system/app/XiaomiServiceFramework
/system/app/Joyose 
/system/app/Notes
/system/app/MiuiVideoLeo 
/system/app/WMService 
/system/priv-app/GoogleFeedback 
/system/priv-app/MiDrop 
/system/app/CloudService 
/system/app/HybridAccessory 
/system/app/TouchAssistant 
/system/app/PartnerBookmarksProvider
/system/priv-app/CloudServiceSysbase 
/system/app/MiWallpaper 
/system/priv-app/CleanMaster 
/system/priv-app/Weather
/system/priv-app/MiuiScanner 
/system/priv-app/YellowPage 
/system/app/AntiSpam 
/system/app/Email 
/system/priv-app/WeatherProvider
/system/priv-app/MiVRFramework
/system/app/SmsExtra
/system/app/XMRemoteController
"
